"""added yatra stops

Revision ID: 42dbad314aa9
Revises: 82d7dada5957
Create Date: 2026-04-06 18:24:48.071048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42dbad314aa9'
down_revision: Union[str, None] = '82d7dada5957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yatra_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_hindi', sa.String(length=100), nullable=True),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_meters', sa.Integer(), nullable=False),
    sa.Column('distance_from_previous_km', sa.Float(), nullable=True),
    sa.Column('cumulative_km', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('stop_type', sa.String(length=50), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yatra_stops_id'), 'yatra_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yatra_stops_id'), table_name='yatra_stops')
    op.drop_table('yatra_stops')
    # ### end Alembic commands ###
