"""added new email verification fields

Revision ID: 6941c94ae06b
Revises: 42dbad314aa9
Create Date: 2026-04-06 18:49:58.243824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6941c94ae06b'
down_revision: Union[str, None] = '42dbad314aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verification_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'verification_attempts')
    op.drop_column('users', 'verification_expires')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
