"""add chat history and comments thread in feed

Revision ID: ede201d146c5
Revises: 8c48b4a1a9b0
Create Date: 2026-06-17 05:25:54.133312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede201d146c5'
down_revision: Union[str, None] = '8c48b4a1a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
